spring:
  datasource:
    url: jdbc:postgresql://dpg-d8o9gf9o3t8c73ddvlag-a/mavutidb
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

logging:
  level:
    za.ac.vut.mavuti: INFO
    root: WARN